### ISSUE TITLE
machine translation is not working

### ISSUE THREAD

**Issue by jannesblobel** [samuelstroschein/inlang-plugin-json#26] opened 2023-05-26 08:51 UTC
I tried to translate missing messages in a repo. And realized the machine translation was not working. 
I am unsure if this is a plugin problem or an inlang core issue. Please let me know if I should open this issue in the main repo.
https://inlang.com/editor/github.com/jannesblobel/AFFiNE

https://www.loom.com/share/e6965b47bbd541c68583ddef9e00a534
@NilsJacobsen @NiklasBuchfink I can't assign you :(
Reproduce: 
1. Open this repo https://inlang.com/editor/github.com/jannesblobel/AFFiNE
2. until the empty messages come 
3. click on "machine translate"

**Comment by NiklasBuchfink** [comment] 2023-05-26 09:09
I couldn't reproduce this issue with the link provided.

1. Forked the repo
2. Commited all german translation by using machine translate
3. Pushed everything to my fork

**Comment by jannesblobel** [comment] 2023-05-26 09:24
Ok, this is weird. I tried again and have the same issues :/ 
I will investigate in the afternoon 

Maybe that's because I used Safarie

**Comment by NiklasBuchfink** [comment] 2023-05-26 09:25
Btw, you can use the new [plugin-i18next](https://github.com/inlang/plugin-i18next) for that repository.

**Comment by jannesblobel** [comment] 2023-05-26 09:57
Should we ask such a question in the Issues Template inlang/inlang? 
What browser was used?

**Comment by NilsJacobsen** [comment] 2023-05-31 14:11
I think that decisions will be a lot easier for the users when we have the plugin registry

**Comment by jannesblobel** [comment] 2023-06-05 15:56
Frankly speaking, yes 
it is still exists

**Comment by NiklasBuchfink** [comment] 2023-06-05 16:13
I still can't reproduce it.

> It works on my machine

_every programmer ever_


 Let's do it the way you mentioned in the Loom. Close it for now, and if this becomes a problem again, we'll take a closer look

**Closed by NiklasBuchfink** 2023-06-05 16:13 UTC
Labels: bug
